# Generated by Django 3.2.8 on 2021-10-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerForVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('typeVaccine', models.CharField(max_length=255)),
                ('sickBefore', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
