# Generated by Django 3.2.8 on 2021-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_registerforvaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('typeVaccine', models.CharField(max_length=255)),
                ('sickBefore', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registerforvaccine',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registerforvaccine',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='registerforvaccine',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registerforvaccine',
            name='sickBefore',
        ),
        migrations.RemoveField(
            model_name='registerforvaccine',
            name='typeVaccine',
        ),
    ]
