# Generated by Django 3.2.8 on 2021-10-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_person_sickbefore'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
