# Generated by Django 3.2.8 on 2021-10-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_person_my_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='my_field',
        ),
        migrations.AlterField(
            model_name='person',
            name='typeVaccine',
            field=models.CharField(choices=[('a', 'نعم'), ('b', 'لا')], max_length=1),
        ),
    ]
