# Generated by Django 3.2.8 on 2021-10-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20211024_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sickBefore',
            field=models.CharField(choices=[('a', 'نعم'), ('b', 'لا')], default='b', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='typeVaccine',
            field=models.CharField(choices=[('1', 'فايزر'), ('2', 'سبوتنيك'), ('3', 'سبوتنيك لايت'), ('4', 'موديرنا')], max_length=1),
        ),
    ]
