# Generated by Django 3.2.8 on 2021-10-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20211024_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sickBefore',
            field=models.CharField(choices=[('a', 'نعم'), ('b', 'لا')], default=0, max_length=1),
        ),
    ]
