# Generated by Django 3.2.8 on 2021-10-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_person_sickbefore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='sickBefore',
            field=models.CharField(choices=[('a', 'نعم'), ('b', 'لا')], max_length=1),
        ),
    ]
