# Generated by Django 4.0.4 on 2022-05-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
